py_binary(
    name = "main",
    srcs = ["main.py"],
    data = ["//src/main/java/com/google/devtools/build/lib:builtin.pb"],
    deps = [
        "//src/main/protobuf:builtin_py_proto",
        "//tools/python/runfiles",
    ],
)